# Generated by Django 2.0.6 on 2018-07-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamoarticulo',
            old_name='estado_reserva',
            new_name='estado_prestamo',
        ),
        migrations.RenameField(
            model_name='prestamoespacio',
            old_name='estado_reserva',
            new_name='estado_prestamo',
        ),
    ]
