# Generated by Django 2.0.5 on 2018-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_espacio', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Prestado'), (3, 'Reparación')], default=1)),
                ('nombre_espacio', models.CharField(max_length=200)),
                ('descripcion_espacio', models.CharField(default='', max_length=1500)),
                ('capacidad_espacio', models.IntegerField(default=0)),
                ('foto_espacio', models.ImageField(default='', upload_to='uploads/fotos_espacios')),
            ],
        ),
    ]
