# Generated by Django 2.0.3 on 2018-05-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_espacio', models.CharField(max_length=200)),
                ('descripcion_espacio', models.CharField(max_length=1500)),
                ('id_espacio', models.IntegerField()),
                ('capacidad_espacio', models.IntegerField()),
                ('estado_espacio', models.CharField(default='Disponible', max_length=10)),
                ('foto_espacio', models.CharField(max_length=1000)),
            ],
        ),
    ]
