# Generated by Django 2.0.3 on 2018-05-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0002_auto_20180504_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacios',
            name='capacidad_espacio',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='descripcion_espacio',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='estado_espacio',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='foto_espacio',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='id_espacio',
        ),
    ]
