# Generated by Django 2.0.3 on 2018-05-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0003_auto_20180514_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacios',
            name='capacidad_espacio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espacios',
            name='descripcion_espacio',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='espacios',
            name='estado_espacio',
            field=models.IntegerField(choices=[(1, 'Disponible'), (2, 'Prestado'), (3, 'Reparación')], default=1),
        ),
        migrations.AddField(
            model_name='espacios',
            name='foto_espacio',
            field=models.ImageField(default='', upload_to='uploads/fotos_espacios'),
        ),
        migrations.AddField(
            model_name='espacios',
            name='id_espacio',
            field=models.IntegerField(default=0),
        ),
    ]
