# Generated by Django 2.0.5 on 2018-06-14 15:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_auto_20180518_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacios',
            name='id_espacio',
        ),
    ]
