# Generated by Django 2.0.3 on 2018-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=200)),
                ('descripcion_articulo', models.CharField(max_length=1500)),
                ('id_articulo', models.IntegerField()),
                ('estado_articulo', models.CharField(default='Disponible', max_length=10)),
                ('foto_articulo', models.CharField(max_length=1000)),
            ],
        ),
    ]
