# Generated by Django 2.0.5 on 2018-06-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_articulo', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Prestado'), (3, 'Reparación'), (4, 'Perdido')], default=1)),
                ('nombre_articulo', models.CharField(max_length=200)),
                ('descripcion_articulo', models.CharField(max_length=1500)),
                ('foto_articulo', models.ImageField(upload_to='uploads/fotos_articulos')),
            ],
        ),
    ]
