# Generated by Django 2.0.5 on 2018-05-13 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20180513_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='correo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
