# Generated by Django 2.0.5 on 2018-06-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('userprofile', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('estado_reserva', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.Articulos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('estado_reserva', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacios')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil')),
            ],
        ),
    ]
