# Generated by Django 2.0.5 on 2018-06-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180513_1702'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaespacio',
            old_name='id_espacio',
            new_name='espacio',
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
        ),
    ]
