# Generated by Django 2.0.5 on 2018-06-03 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_remove_espacios_id_espacio'),
        ('userprofile', '0003_auto_20180513_1702'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaespacio',
            name='id_espacio',
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AddField(
            model_name='reservaarticulo',
            name='perfil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='espacio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='espacios.Espacios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='estado_reserva',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Entregado'), (3, 'Rechazado')], default=1),
        ),
        migrations.AddField(
            model_name='reservaespacio',
            name='perfil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
            preserve_default=False,
        ),
    ]
