# Generated by Django 2.0.6 on 2018-06-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_auto_20180613_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaarticulo',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
        ),
        migrations.AlterField(
            model_name='reservaespacio',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Perfil'),
        ),
    ]
